Update bindings to 2.12
TileDB-Inc/TileDB-CSharp pull request #130
Opened 2022-11-01 10:39 UTC by teo-tsirpanis

2022-11-01 10:40 UTC, teo-tsirpanis commented on sources/TileDB.CSharp/Enums.cs
> +        Delete = tiledb_query_type_t.TILEDB_DELETE,
I gave C#-friendly names to the new enum values, will update the others soon (and obsolete the `TILEDB_***` values).

2022-11-02 15:26 UTC, shaunrd0 requested changes
Looks good! I like the changes to `generate.rsp`, these options will make the regeneration commands much simpler. :+1: I regenerated locally and had the same results.

We should also update `.csproj` and `.nuspec` files, this is something I forgot to do on my 2.12 branch so [here](https://github.com/TileDB-Inc/TileDB-CSharp/pull/100/files#diff-1d244d9aab29d2ed08444d57b10ceb3ed925e3bb990287d6ea94f5097a13fb55) is an example of the changes I made to these files before rolling out a new release for 2.11.3.

2022-11-04 09:14 UTC, teo-tsirpanis commented on cpp/cmake/TileDB.cmake
> +elseif(${TILEDB_VERSION} STREQUAL "2.11.3")
Done.

2022-11-04 09:15 UTC, teo-tsirpanis commented
I updated the library's version to 5.3.0 and removed it from the example projects; they don't need one.

2022-11-04 18:17 UTC, merged